controller_list:
  - name: RTRDoubleArmV7/tohoku_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - MFRAME
      - BLOCK
      - BOOM
      - ARM
      - TOHKU_PITCH
      - TOHKU_ROLL
  - name: RTRDoubleArmV7/mani_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - UFRAME
      - MNP_SWING
      - MANIBOOM
      - MANIARM
      - MANIELBOW
      - YAWJOINT
      - HANDBASE
